### ISSUE TITLE
Works

### ISSUE THREAD

**Issue by ernierasta** [aerth/rpg#1]
Hi, just booted Windows 10 64-bit for You - it works (you asked about that in release comment)! :-)

I see, that development has slowed down. Will you develop this further?

Have a good day!

**Comment by aerth** [comment]
Thanks, I am super glad it works on windows. Development has definitely slowed down (stopped), but I'd be love to see some PRs for improvements.

Next on the roadmap **_was_** "regions" separated by "doors/portals" which would allow creating spawns in certain regions (and prevent them from leaving before you open the door) and jumping to different maps.

It was very fun working on this project, would love to be able to return to it when I have some time!

Also see (also unmaintained) multiplayer version here: https://github.com/mmogo/mmo

**Comment by ernierasta** [comment]
Hi! While interesting project (and in go!), no time to maintain this. But maybe someone else will pick it up or you will come back later! My limited spare time will now go to: https://github.com/Grokmoo/sulis (I am not author, just hanging around and trying to do something useful with it. :-)
